"""initial schema with apscheduler_jobs

Revision ID: 4e221ad41c62
Revises:
Create Date: 2026-06-22 23:27:43.923061

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'api_source_health',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('last_success_at', sa.DateTime(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('source'),
    )
    op.create_table(
        'apscheduler_jobs',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column('next_run_time', sa.DateTime(), nullable=True),
        sa.Column('job_state', sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table(
        'draw_results',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lottery_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column('draw_no', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('draw_date', sa.DateTime(), nullable=False),
        sa.Column('numbers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('fetched_at', sa.DateTime(), nullable=False),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.Column('single_source', sa.Boolean(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('lottery_code', 'draw_no', name='uq_draw_lottery_no'),
    )
    op.create_index(op.f('ix_draw_results_draw_no'), 'draw_results', ['draw_no'], unique=False)
    op.create_index(op.f('ix_draw_results_lottery_code'), 'draw_results', ['lottery_code'], unique=False)
    op.create_table(
        'lottery_types',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column('spec_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('draw_schedule_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('schema_version', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('code'),
    )
    op.create_table(
        'users',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table(
        'admin_audit_logs',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('old_values', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('new_values', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ['admin_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_table(
        'draw_corrections',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('draw_result_id', sa.Integer(), nullable=False),
        sa.Column('old_numbers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('new_numbers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('corrected_at', sa.DateTime(), nullable=True),
        sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ['draw_result_id'],
            ['draw_results.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_draw_corrections_draw_result_id'), 'draw_corrections', ['draw_result_id'], unique=False)
    op.create_table(
        'notification_channels',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('key_version', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_notification_channels_user_id'), 'notification_channels', ['user_id'], unique=False)
    op.create_table(
        'notification_logs',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_table(
        'notification_rules',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('lottery_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column('timing', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ['lottery_code'],
            ['lottery_types.code'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_notification_rules_lottery_code'), 'notification_rules', ['lottery_code'], unique=False)
    op.create_index(op.f('ix_notification_rules_user_id'), 'notification_rules', ['user_id'], unique=False)
    op.create_table(
        'pending_comparisons',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('draw_result_id', sa.Integer(), nullable=False),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['draw_result_id'],
            ['draw_results.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_pending_comparisons_draw_result_id'), 'pending_comparisons', ['draw_result_id'], unique=False
    )
    op.create_index(op.f('ix_pending_comparisons_processed_at'), 'pending_comparisons', ['processed_at'], unique=False)
    op.create_table(
        'tickets',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('lottery_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column('play_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('numbers_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tuo_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column('multiplier', sa.Integer(), nullable=False),
        sa.Column('append', sa.Boolean(), nullable=False),
        sa.Column('cost', sa.Integer(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['lottery_code'],
            ['lottery_types.code'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_tickets_lottery_code'), 'tickets', ['lottery_code'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_table(
        'comparisons',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('draw_result_id', sa.Integer(), nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('hits_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('prize_tier', sa.Integer(), nullable=True),
        sa.Column('prize_amount', sa.Integer(), nullable=True),
        sa.Column('is_win', sa.Boolean(), nullable=False),
        sa.Column('corrected_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['draw_result_id'],
            ['draw_results.id'],
        ),
        sa.ForeignKeyConstraint(
            ['ticket_id'],
            ['tickets.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('draw_result_id', 'ticket_id', name='uq_cmp_draw_ticket'),
    )
    op.create_index(op.f('ix_comparisons_draw_result_id'), 'comparisons', ['draw_result_id'], unique=False)
    op.create_index(op.f('ix_comparisons_ticket_id'), 'comparisons', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_comparisons_user_id'), 'comparisons', ['user_id'], unique=False)
    op.create_table(
        'prize_claims',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('comparison_id', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('deadline', sa.DateTime(), nullable=False),
        sa.Column('claimed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['comparison_id'],
            ['comparisons.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_prize_claims_comparison_id'), 'prize_claims', ['comparison_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prize_claims_comparison_id'), table_name='prize_claims')
    op.drop_table('prize_claims')
    op.drop_index(op.f('ix_comparisons_user_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_ticket_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_draw_result_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_lottery_code'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_pending_comparisons_processed_at'), table_name='pending_comparisons')
    op.drop_index(op.f('ix_pending_comparisons_draw_result_id'), table_name='pending_comparisons')
    op.drop_table('pending_comparisons')
    op.drop_index(op.f('ix_notification_rules_user_id'), table_name='notification_rules')
    op.drop_index(op.f('ix_notification_rules_lottery_code'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_notification_channels_user_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_draw_corrections_draw_result_id'), table_name='draw_corrections')
    op.drop_table('draw_corrections')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.drop_table('users')
    op.drop_table('lottery_types')
    op.drop_index(op.f('ix_draw_results_lottery_code'), table_name='draw_results')
    op.drop_index(op.f('ix_draw_results_draw_no'), table_name='draw_results')
    op.drop_table('draw_results')
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_table('api_source_health')
    # ### end Alembic commands ###
