"""Add dnd_json column to users table.

Revision ID: 2024_add_user_dnd_json
Revises: e0185f67bb27
Create Date: 2026-07-05 19:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2024_add_user_dnd_json'
down_revision: str | Sequence[str] | None = 'e0185f67bb27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('dnd_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dnd_json')
    # ### end Alembic commands ###
